import '../lazyload.js'
import '../dragOff.js'
// import '../../blocks/agreement/agreement.js'
// import '../../blocks/aside/aside.js'
// import '../../blocks/form/form.js'
// import '../../blocks/header/header.js'
// import '../smoothScroll.js'
// import '../../blocks/input-file/input-file.js'
// import '../../blocks/input-text/input-text.js'
// import '../../blocks/popup/popup.js'
// import '../../blocks/select/select.js'
// import '../../blocks/slider/slider.js'
// import '../../blocks/tooltip/tooltip.js'